//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsSale_
    {
        public double Код_реализации { get; set; }
        public string Продукция { get; set; }
        public string Наименование_агента { get; set; }
        public Nullable<System.DateTime> Дата_реализации { get; set; }
        public Nullable<double> Количество_продукции { get; set; }
    }
}
