//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        public string Код_сотрудника { get; set; }
        public string ФИО { get; set; }
        public string ДатаРождения { get; set; }
        public string ПаспортныеДанные { get; set; }
        public string БанковскиеРеквизиты { get; set; }
        public string НаличиеСемьи { get; set; }
        public string ПроблемыСоЗдоровьем { get; set; }
    }
}
